version: '24.0'
services: 
  dev-db:
   image: postgres:16
   ports:
    - 5434:5432
   environment: 
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: 123
    POSTGRES_DB: nest
   networks:
    - practicecamp
    test-db:
   image: postgres:16
   ports:
    - 5435:5432
   environment: 
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: 123
    POSTGRES_DB: nest
   networks:
    - practicecamp
networks:
  practicecamp: